name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  OPENCV_INCLUDE_PATHS: C:\tools\opencv\build\include
  OPENCV_LINK_LIBS: opencv_world4100
  OPENCV_LINK_PATHS: C:\tools\opencv\build\x64\vc16\lib

jobs:
  build:
    name: "Build Automate"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Configure choco cache"
        run: choco config set cacheLocation ./.choco-cache

      - uses: actions/cache@v4
        with:
          path: ./.choco-cache
          key: choco-cache

      - name: "Install llvm and opencv via chocolate"
        run: choco install llvm opencv

      - name: Build
        run: cargo build --verbose
